### ISSUE TITLE
panic: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by chrisjaimon2012** [kovetskiy/mark#161]
Version: `>6.6`

For a README files without metadata, the expected way it handles error would be
```
FATAL specified file doesn't contain metadata and URL is not specified via command line or doesn't contain pageId GET-parameter
```

But on builds after `v6.6`, it panics
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x100de46c8 ]

goroutine 1 [running]:
main.processFile({0x16b523a13, 0x9}, 0x1400037c040, {{0x16b523a13, 0x9}, 0x0, 0x0, 0x1, 0x0, 0x0, ...}, ...)
	/home/runner/work/mark/mark/main.go:182 +0x1a8
main.main()
	/home/runner/work/mark/mark/main.go:150 +0x610
```

8d58ff26a3721a6f49fb1124d5f5287c28c05e0d seems to be the breaking commit, will raise a PR for a fix soon

**Comment by kovetskiy** [comment]
Should be fixed now by #162
