### ISSUE TITLE
What's means about this error log when I execute command import makrdown to confluence.

### ISSUE THREAD

**Issue by superlzs0476** [kovetskiy/mark#213]
2022-08-11 20:22:13.425 FATAL specified file doesn't contain metadata and URL is not specified via command line or doesn't contain pageId GET-parameter

**Comment by iainelder** [comment]
@superlzs0476 Can you share the command you used to generate this error?

**Comment by gshel** [comment]
Hey I encountered a similar error when I had a macro at the very top of my file; moving the macro to the bottom, after the space, title, and parent fixed it for me.

**Comment by joyfulrabbit** [comment]
--trace --debug often don't work for this because it is looking for a parameter that is missing.

Right now I'm not having any issues if I put metadata into my .md files, however when attempting to use the command line, it frequently doesn't like what I've provided. 

It would be helpful to know what meta data is in your .md file, what command you're running from the CLI, and possibly what your config file contains.

I will post back here if I have more to offer wrt bad formatting of base URL /  edit location which is what I'm currently working through.

**Comment by joyfulrabbit** [comment]
The format of your URL matters if you don't have meta data in your headers. This is not super clearly documented, I'd like more examples of this.

This URL format with no meta-data :
<confluence-url>/pages/viewpage.action?pageId=<pageId>

Throws this this error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x100b5ecf4]

goroutine 1 [running]:
main.processFile({0x1400001c780, 0x48}, 0x1008860f8?, {{0x16f5af560, 0x2d}, 0x0, 0x0, 0x0, 0x1, 0x1, ...}, ...)
        github.com/kovetskiy/mark/main.go:208 +0x1f4
main.main()
        github.com/kovetskiy/mark/main.go:159 +0x51
```
