### ISSUE TITLE
App crashes when using mixed parameters (metadata + command line arguments)

### ISSUE THREAD

**Issue by drspoton** [kovetskiy/mark#240]
```sh
mark -p xxx -l 'https://xxx/wiki/pages/viewpage.action?pageId=123' --space 'xxx' -f plik.md
```

```
2023-01-10 10:58:31.000 INFO  processing plik.md
2023-01-10 10:58:31.000 WARN  specified file contains metadata, but it will be ignored due specified command line URL
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1375db2]

goroutine 1 [running]:
main.processFile({0x205b0bacb, 0x7}, 0xc000265f70?, {{0x205b0bacb, 0x7}, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
	/Users/xxx/Desktop/mark/main.go:212 +0x2f2
main.main()
	/Users/xxx/Desktop/mark/main.go:158 +0x61c
exit status 2
```

See lines:
https://github.com/kovetskiy/mark/blob/master/main.go#L195
https://github.com/kovetskiy/mark/blob/master/main.go#L212

```go
	if pageID != "" && meta != nil {
		log.Warning(
			`specified file contains metadata, ` +
				`but it will be ignored due specified command line URL`,
		)

		meta = nil ⬅️
	}
// ...
	switch {
	case meta.Space == "" && flags.Space == "":  ⬅️
		log.Fatal(
			"space is not set ('Space' header is not set and '--space' option is not set)",
		)
```

**Comment by mrueg** [comment]
Please try again with mark-9.8.0 or later. Feel free to reopen if the issue still exists.
