### ISSUE TITLE
panic: interface conversion: ast.Node is *ast.CodeBlock, not *ast.FencedCodeBlock

### ISSUE THREAD

**Issue by valorcz** [kovetskiy/mark#266]
I just tried the latest release of Mark and tried it on something that worked well previously, but now I am getting this error:

```
panic: interface conversion: ast.Node is *ast.CodeBlock, not *ast.FencedCodeBlock
```

Here's the stack trace:

```
goroutine 1 [running]:
github.com/kovetskiy/mark/pkg/mark.(*ConfluenceRenderer).renderCodeBlock(0xc000399050?, {0x16393f0?, 0xc0003ab500?}, {0xc000415800?, 0x151f?, 0x1800?}, {0x163d918?, 0xc0002b7f80?}, 0x0?)
	/Users/lorenc/go/pkg/mod/github.com/kovetskiy/mark@v0.0.0-20230328145404-93218f1e69a9/pkg/mark/markdown.go:317 +0x829
github.com/yuin/goldmark/renderer.(*renderer).Render.func2({0x163d918, 0xc0002b7f80}, 0x78?)
	/Users/lorenc/go/pkg/mod/github.com/yuin/goldmark@v1.5.4/renderer/renderer.go:166 +0xc7
github.com/yuin/goldmark/ast.walkHelper({0x163d918, 0xc0002b7f80}, 0xc00033f778)
	/Users/lorenc/go/pkg/mod/github.com/yuin/goldmark@v1.5.4/ast/ast.go:492 +0x34
github.com/yuin/goldmark/ast.walkHelper({0x163db58, 0xc0002bb4d0}, 0xc00033f778)
	/Users/lorenc/go/pkg/mod/github.com/yuin/goldmark@v1.5.4/ast/ast.go:498 +0x8e
github.com/yuin/goldmark/ast.Walk(...)
	/Users/lorenc/go/pkg/mod/github.com/yuin/goldmark@v1.5.4/ast/ast.go:487
github.com/yuin/goldmark/renderer.(*renderer).Render(0xc0002b0d70, {0x1634580?, 0xc0004012f0?}, {0xc000415800, 0x151f, 0x1800}, {0x163db58, 0xc0002bb4d0})
	/Users/lorenc/go/pkg/mod/github.com/yuin/goldmark@v1.5.4/renderer/renderer.go:161 +0x225
github.com/yuin/goldmark.(*markdown).Convert(0xc0003ab000, {0xc000415800, 0x151f, 0x1800}, {0x1634580, 0xc0004012f0}, {0x0, 0x0, 0x0})
	/Users/lorenc/go/pkg/mod/github.com/yuin/goldmark@v1.5.4/markdown.go:117 +0x10b
github.com/kovetskiy/mark/pkg/mark.CompileMarkdown({0xc0003b6000, 0x14f8, 0x1500}, 0xc0002ae4a0)
	/Users/lorenc/go/pkg/mod/github.com/kovetskiy/mark@v0.0.0-20230328145404-93218f1e69a9/pkg/mark/markdown.go:423 +0x67a
main.processFile({0xc000354fc0, 0x35}, 0xc00033ff70?, {{0x7ff7bfeff80f, 0x6}, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
	/Users/lorenc/go/pkg/mod/github.com/kovetskiy/mark@v0.0.0-20230328145404-93218f1e69a9/main.go:356 +0xe1d
main.main()
	/Users/lorenc/go/pkg/mod/github.com/kovetskiy/mark@v0.0.0-20230328145404-93218f1e69a9/main.go:158 +0x5fc
```

Unfortunately, I don't know much about golang.

One thing that could be causing this is that one code block has an "inner code-block", e.g.

```default
this is a code block
```a comment in the language/Splunk query here```
rest of the code block
```

it worked well with the previous markdown parser, but seems the new one doesn't like this construction.

**Comment by mrueg** [comment]
Please test with 9.0.1 and let us know if it works.
I've added a test for CodeBlocks as well.

**Comment by valorcz** [comment]
It indeed helped with the code block, thank you!

Now I am getting some error response from Confluence because of tables rendering, but I'll file a new issue when I collect the evidence.
